version: '3'
services:
  flask:
    image: python:3.9.13
    restart: always
    expose:
      - '80'
    volumes:
      - .:/code
      - /etc/localtime:/etc/localtime:ro
      - node_modules:/code/app/static/node_modules
    working_dir: "/code"
    env_file:
      - ./docker/config.env
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        python -m pip install -r requirements.txt
        python main.py
  nodejs:
    image: node:16.13.2
    volumes:
    - ./app/static/package.json:/static/package.json
    - node_modules:/static/node_modules
    working_dir: '/static'
    command: 'npm install'
  nginx:
    image: 'nginx'
    restart: always
    ports:
      - '20080:80'
    links:
      - 'flask'
    volumes:
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
volumes:
  node_modules: