version: '3'
services:
  flask:
    image: python:3.9.13
    restart: always
    expose:
      - '${app_http_port}'
    volumes:
      - .:/code
      - /etc/localtime:/etc/localtime:ro
    working_dir: "/code"
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        python -m pip install -r requirements.txt
        python application.py
  nodejs:
    image: node:16.13.2
    volumes:
    - .:/code
    working_dir: '/code'
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        npm install
        npm run deploy
  nginx:
    image: 'nginx'
    restart: always
    ports:
      - '${NGINX_PORT}:${app_http_port}'
    links:
      - 'flask'
    volumes:
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
